# Force vi mode
setw -g mode-keys vi

# Use 'v' to begin selection (like Vim)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Use 'y' to yank (copy) and exit copy-mode
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Also bind Enter to use xclip
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Allow mouse scroll 
set -g mouse on

# Copy to system clipboard (not only tmux buffer) when releasing mouse button
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
